### ISSUE TITLE
SVG demo holds CPU at 100% utilization indefinitely

### ISSUE THREAD

**Issue by dan-gies** [google/forma#36]
# System Information
* Windows 10, OS build 19044.1586
* Intel Core i7-7500U CPU @ 2.90 GHz
* Intel HD Graphics 620 (Integrated), 8 GB VRAM
* 16 GB RAM, 2133 MHz

# Description
Running `cargo run --release -p demo -- svg assets/svgs/paris-30k.svg` successfully compiles and displays the expected SVG map, however, all 4 logical processors are pegged at 100%, indefinitely, until I terminate the program.

**Comment by dragostis** [comment]
That's working as intended: the SVG demo re-draws everything every frame so you can get an idea of the performance of rendering something as large as the partis-30k map. Animating each element of the map should have similar performance for example.
